### ISSUE TITLE
Expose some config options to users

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/ldk-node#17]
LDK allows to configure many different things, e.g., through `UserConfig`. 

We should therefore only expose a subset, **not** all of them to `LdkLite` users.

This issue is meant to track/discuss what config options exactly we should expose in the API, and for which we should just pick/adapt sane defaults.

**Comment by G8XSU** [comment]
What is the problem with picking sane defaults by default and having option to configure ? 
That is have the defaults in default-config and not in code?

**Comment by tnull** [comment]
Well, I'd argue config options are a part of the API. Since there are quite a few with which users could shoot themselves in the foot, we should at least consider only exposing a subset of all LDK/BDK/etc config knobs to LDKLite users. If we end up exposing all that is maybe also fine, but it should be a dedicated decision we made.
