### ISSUE TITLE
Allow to pay LNURLs/Lightning Addresses

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/ldk-node#181]
While we probably won't support LNURL for receiving (due to the HTTP server requirement), we should see to support *sending* to LNURL and Lightning Addresses.

Might be blocked on Tor integration (i.e., ~#178) as we'd probably want to make the service calls via *an* ~anonymizing proxy, Tor being the likely candidate here.

**Comment by slanesuke** [comment]
If no one is assigned, I can pick  up #178 then this?
