### ISSUE TITLE
Add helpers for BIP21/Unified QR Support

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/ldk-node#182]
While we probably shouldn't add dependencies for generating the actual QR codes, we should add helper methods that make it trivial to generate and parse the raw BIP21 data so that integration with any (native) QR code scanning/generation logic can easily be integrated.

Also see:
https://bitcoinqr.dev/
https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki

**Comment by bennyhodl** [comment]
What is the best way to go about this? Should this be a trait for onchain addresses and lightning invoice structs to implement?

As well as an impl function in `Node` to create a BIP21 invoice?

**Comment by jbesraa** [comment]
I understand the reasoning behind not adding a new dep for this, but it would be nice to actually have some standard around different projects. at payjoin we are using https://github.com/Kixunil/bip21 and planning to maintain it

**Comment by DanGould** [comment]
Seems like this has been unblocked

**Comment by danielnordh** [comment]
I can see support has been merged in Rust, but can't seem to find it in Swift, 0.3.0.
Is it waiting to be exposed in the bindings?
