### ISSUE TITLE
Check if we also need to apply `Info.plist` fixes

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/ldk-node#279]
Apple is fun. We should see if we need to fix this, too: https://github.com/bitcoindevkit/bdk-ffi/pull/466

**Comment by reez** [comment]
I believe this to be the same case for LDK Node + Xcode 15.3, via testing it out with Monday on Xcode 15.3. I'm planning on helping out in whatever way needed but still working out the mechanics (and unknowns) of what a permanent+stable solution looks like for this.


<img width="452" alt="Screenshot 2024-03-20 at 11 31 10 AM" src="https://github.com/lightningdevkit/ldk-node/assets/6657488/91027edc-60c3-428b-a5f1-25d3b264cd6d">

**Comment by reez** [comment]
I think we've got a fix for it deployed now, will see what the feedback is for any of the users who were experiencing this issue in the new Xcode (15.3): https://github.com/bitcoindevkit/bdk-ffi/issues/463#issuecomment-2025622537

I'm also interested to see if Xcode 15.4 (whenever it releases) rolls back the mechanism that created this issue in Xcode 15.3.

**Comment by reez** [comment]
> I think we've got a fix for it deployed now, will see what the feedback is for any of the users who were experiencing this issue in the new Xcode (15.3): [bitcoindevkit/bdk-ffi#463 (comment)](https://github.com/bitcoindevkit/bdk-ffi/issues/463#issuecomment-2025622537)
> 
> I'm also interested to see if Xcode 15.4 (whenever it releases) rolls back the mechanism that created this issue in Xcode 15.3.

Xcode 15.4 just released a day or so ago, but it did not roll back the mechanism that created the issue, so it does look like a fix will need to be applied to LDK Node since it seems as though Apple is definitely moving forward with their changes-

**Comment by FlorianHubl** [comment]
When does the problem get fixed? Without this issue being fixed I cannot use ldk node.
