### ISSUE TITLE
Allow to manually register and claim payments

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/ldk-node#280]
We should allow users to register interest in payments for which they got the preimage out-of-bounds. We'd then issue a `PaymentClaimable` event similar to the one in LDK and would allow them to manually claim such payments.

Things to figure out:

1) Should we keep a list of payment hashes for which we always issue `PaymentClaimable`, or issue `PaymentClaimable` if we can't claim with our default logic already
2) Can we avoid `PaymentClaimable` being issued if users don't expect it? Should we have a config flag? Or could we even always issue it but auto-fail the payment if it's issued and the user calls `event_handled` without claiming the payment?
3) If/how we want to track them in the payment store

**Comment by lazyfuhrer** [comment]
I think when the user registers interest in payment for the preimage, we can store the corresponding payment in `PaymentStore` and then we can always issue `PaymentClaimable` event and should the user calls `event_handled` method without claiming the payment, we can make the payment fail. Let me know your thoughts. Based on your input and design approach I can start working on this PR. @tnull
