### ISSUE TITLE
Allow to set node alias

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/ldk-node#304]
We should add a `Config` field allowing to set the alias a node would use in its announcement.

~~For bindings, we'll need to make this a `Vec<u8>`. We could consider making this an `Option<Vec<u8>>` and refuse to a) open public channels if it's unset b) startup with public channels if it's unset or doesn't fit in the `[u8; 32]`.~~

**Comment by enigbe** [comment]
Hi @tnull, I'd like to pick this up if no one is currently assigned to or working on it.

**Comment by enigbe** [comment]
Hi @tnull, I have a [draft PR](https://github.com/lightningdevkit/ldk-node/pull/330) ready for a cursory look. I am still figuring out how binding generation works but didn't want that to hold up progress especially if you disagree with the direction this is taking. Please share some feedback when you can.
