### ISSUE TITLE
Figure out NAT traversal

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/ldk-node#42]
We need to figure out NAT traversal for incoming channels, in particular on mobile. 

In the LSP model, it *should hopefully* be possible that we open the connection, then request a new channel with a bogus IP address, and the LSP figures out that he already has an open connection to our node ID and opens the channel via that. However, we probably can't trust on that working for every LSP, in particular since they may have multiple nodes which we can't know beforehand.

So we need to figure out a way to receive incoming channels. Maybe hole punching? STUN? UPnP?

**Comment by moneyball** [comment]
What does the LSP spec say? :-P
