### ISSUE TITLE
Consider adding `last_updated` field to `PaymentDetails`

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/ldk-node#57]
This would allow the user to query for 'recent' payments based on a suitable filter.

In order to do this nicely we should however consider implementing `Writeable`/`Readable` for `SystemTime` upstream.

**Comment by jbesraa** [comment]
Can you please say more about the `Writeable/Readable` for `SystemTime` ? 

If we add `last_updated` to `PaymentDetails` and `PaymentDetailsUpdate`, while in the later its set to `last_updated: SystemTime::now()
				.duration_since(UNIX_EPOCH)
				.expect("Time went backwards")
				.as_secs(),
` 
wouldnt that work?

iam actually assuming you are referring to unix time but not sure thats correct?
